#include "ferretapp.h"
#include "helpframe.h" // include here so compiler can access HelpFrame methods

IMPLEMENT_APP(FerretApp)

FerretApp::FerretApp ()
{
	_text_type = true; // assume text type at start
	// create the temporary folder for extracting files to
	_extract_folder = wxFileName::GetCwd () + wxFILE_SEP_PATH + wxT("FerretAppTempFolder");
	if (!wxFileName::DirExists (_extract_folder))
		wxFileName::Mkdir (_extract_folder);
	_copy_all = false;
	_convert_all = false;
	_ignore_unknown = true;
	_last_x = 0;
	_last_y = (
	#if __WXMAC__ 
	22
	#else
	 0
	#endif
	);
}

void FerretApp::CloseHelp ()
{
	_ferret_help->Destroy ();
}

void FerretApp::ShowSelectionHelp ()
{
	_ferret_help->ShowSelectionHelp ();
}

void FerretApp::ShowTableHelp ()
{
	_ferret_help->ShowTableHelp ();
}

void FerretApp::ShowComparisonHelp ()
{
	_ferret_help->ShowComparisonHelp ();
}

wxString FerretApp::GetVersionString ()
{
	return wxT("Ferret 5.3");
}

wxString FerretApp::GetGeneratedByString ()
{
	return wxT("Generated by ") +
		GetVersionString () +
		wxT(", (c) School of Computer Science, University of Hertfordshire, 2013.");
}

wxString FerretApp::GetExtractFolder () const
{
	return _extract_folder;
}

void FerretApp::SetExtractFolder (wxString extract_folder)
{
	_extract_folder = extract_folder;
}

bool FerretApp::GetCopyAll () const
{
	return _copy_all;
}

void FerretApp::SetCopyAll (bool copy_all)
{
	_copy_all = copy_all;
}

bool FerretApp::GetConvertAll () const
{
	return _convert_all;
}

void FerretApp::SetConvertAll (bool convert_all)
{
	_convert_all = convert_all;
}

bool FerretApp::GetIgnoreUnknown () const
{
	return _ignore_unknown;
}

void FerretApp::SetIgnoreUnknown (bool ignore_unknown)
{
	_ignore_unknown = ignore_unknown;
}

void FerretApp::AddProblemFile (wxString file)
{
	_problem_files.Add (file);
}

const wxSortedArrayString & FerretApp::GetProblemFiles () const
{
	return _problem_files;
}

void FerretApp::AddIgnoredFile (wxString file)
{
	_ignored_files.Add (file);
}

const wxSortedArrayString & FerretApp::GetIgnoredFiles () const
{
	return _ignored_files;
}

// helps stagger created windows on screen -- goes down screen then across
wxPoint FerretApp::GetNextFramePosition (int window_width, int window_height)
{
	wxPoint point (_last_x, _last_y);
	_last_y += 30;
	if (_last_y + window_height > wxGetDisplaySize().y)
	{
		_last_y = (
		#if __WXMAC__ 
		22
		#else
		0
		#endif
		);
		_last_x += 30;
		if (_last_x + window_width > wxGetDisplaySize().x)
		{
			_last_x = 0;
		}
	}
	return point;
}

